# Generated by Django 5.0 on 2024-01-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField()),
                ('district_name', models.CharField(default='District', max_length=100)),
                ('district_city', models.CharField(max_length=100)),
                ('district_num_schools', models.IntegerField()),
                ('district_geo_lat', models.FloatField()),
                ('district_geo_long', models.FloatField()),
                ('district_bb_bottom_left_lat', models.FloatField()),
                ('district_bb_bottom_left_lng', models.FloatField()),
                ('district_bb_top_right_lat', models.FloatField()),
                ('district_bb_top_right_lng', models.FloatField()),
            ],
        ),
    ]
