# Generated by Django 5.0 on 2024-01-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooldistrict',
            old_name='district_bb_bottom_left_lat',
            new_name='district_bb_northeast_lat',
        ),
        migrations.RenameField(
            model_name='schooldistrict',
            old_name='district_bb_bottom_left_lng',
            new_name='district_bb_northeast_lng',
        ),
        migrations.RenameField(
            model_name='schooldistrict',
            old_name='district_bb_top_right_lat',
            new_name='district_bb_southwest_lat',
        ),
        migrations.RenameField(
            model_name='schooldistrict',
            old_name='district_bb_top_right_lng',
            new_name='district_bb_southwest_lng',
        ),
        migrations.AlterUniqueTogether(
            name='schooldistrict',
            unique_together={('district_name', 'district_city')},
        ),
        migrations.AlterField(
            model_name='schooldistrict',
            name='district_name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='schooldistrict',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='schooldistrict',
            name='district_num_schools',
        ),
    ]
