# Generated by Django 5.0 on 2024-01-26 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapannotation',
            old_name='author',
            new_name='annotation_author',
        ),
        migrations.RenameField(
            model_name='mapannotation',
            old_name='coordinates',
            new_name='annotation_coordinates',
        ),
        migrations.RemoveField(
            model_name='mapannotation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mapannotation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mapannotation',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='mapannotation',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='mapannotation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mapannotation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mapannotation',
            name='annotation_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapannotation',
            name='annotation_layer',
            field=models.CharField(choices=[('hvac', 'HVAC'), ('ahu', 'Air Handling Unit'), ('electrical_distribution', 'Electrical Distribution'), ('lighting', 'Lighting'), ('plumbing', 'Plumbing'), ('sanitary_system', 'Sanitary System'), ('water_supply', 'Water Supply'), ('fire_protection', 'Fire Protection'), ('security_system', 'Security System'), ('data_network', 'Data Network'), ('telecommunications', 'Telecommunications'), ('mechanical_ventilation', 'Mechanical Ventilation'), ('escalators_elevators', 'Escalators & Elevators'), ('renewable_energy', 'Renewable Energy'), ('existing_conditions', 'Existing Conditions'), ('proposed_development', 'Proposed Development'), ('demolition_plan', 'Demolition Plan'), ('construction_phase', 'Construction Phase'), ('future_expansion', 'Future Expansion'), ('landscaping', 'Landscaping'), ('site_utilities', 'Site Utilities'), ('parking_layout', 'Parking Layout')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapannotation',
            name='annotation_type',
            field=models.CharField(choices=[('market', 'Marker'), ('line', 'Line'), ('polygon', 'Polygon'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('meter', 'Meter'), ('label', 'Label'), ('sticky_note', 'Sticky Note')], max_length=100),
        ),
    ]
