UTILITY_TYPE = (
        ('Natural Gas', 'Natural Gas'),
        ('Electric', 'Electric'),
        # ('solar', 'Solar'),
)
UTILITY_PROVIDERS = (
    ('PGE', 'PGE'),
    ('SCE', 'SCE'),
    ('SoCalG', 'SoCalG'),
    ('SDGE', 'SDGE'),
)
INTERVAL_TIME_ZONES = (
    ('us_pacific', 'US/Pacific'),
)
BUILDING_TYPES = (
    ('classroom', 'Classroom Building'),
    ('laboratory', 'Laboratory'),
    ('library', 'Library'),
    ('restrooms', 'Restrooms'),
    ('cafeteria', 'Cafeteria'),
    ('gymnasium', 'Gymnasium'),
    ('auditorium', 'Auditorium'),
    ('administrative', 'Administrative'),
    ('maintenance', 'Maintenance'),
    ('storage', 'Storage'),
    ('parking', 'Parking'),
    ('sports', 'Sports'),
    ('playground', 'Playground'),
    ('outdoor', 'Outdoor'),
    ('other', 'Other'),
    ('arts', 'Arts'),
    ('music', 'Music'),
    ('theater', 'Theater'),
    ('workshop', 'Workshop'),
    ('kitchen', 'Kitchen'),
    ('health', 'Health'),
    ('counseling', 'Counseling'),
    ('security', 'Security'),
    ('energy_plant', 'Energy Plant'),
    ('commons', 'Student Commons/Common Area'),
    ('computer_lab', 'Computer Lab'),
    ('science_center', 'Science Center'),
    ('art_studio', 'Art Studio'),
    ('language_lab', 'Language Lab'),
    ('greenhouse', 'Greenhouse'),
    ('childcare', 'Childcare Center'),
    ('outdoor_classroom', 'Outdoor Classroom'),
    ('student_center', 'Student Center'),
    ('technology_hub', 'Technology Hub'),
    ('vocational_training', 'Vocational Training Center')
)
ELECTRICAL_EQUIPMENT_TYPES = (
    ('circuit_breaker', 'Circuit Breaker'),
    ('transformer', 'Transformer'),
    ('voltage_regulator', 'Voltage Regulator'),
    ('electric_meter', 'Electric Meter'),
    ('solar_panel', 'Solar Panel'),
    ('generator', 'Generator'),
    ('surge_protector', 'Surge Protector'),
    ('ups', 'UPS (Uninterruptible Power Supply)'),
    ('conduit_fittings', 'Conduit Fittings'),
    ('junction_box', 'Junction Box'),
    ('lighting_control', 'Lighting Control System'),
    ('battery_storage', 'Battery Storage'),
    ('inverter', 'Inverter'),
    ('power_distribution_unit', 'Power Distribution Unit'),
    ('energy_management_system', 'Energy Management System'),
    ('smart_meter', 'Smart Meter'),
    ('ev_charging_station', 'EV Charging Station'),
    ('security_camera', 'Security Camera'),
    ('network_switch', 'Network Switch'),
    ('fire_alarm_panel', 'Fire Alarm Panel')
)
MECHANICAL_EQUIPMENT_TYPES = (
    ('hvac_unit', 'HVAC Unit'),
    ('boiler', 'Boiler'),
    ('compressor', 'Compressor'),
    ('heat_exchanger', 'Heat Exchanger'),
    ('pump', 'Pump'),
    ('fan_coil_unit', 'Fan Coil Unit'),
    ('air_handling_unit', 'Air Handling Unit'),
    ('chiller', 'Chiller'),
    ('ductwork_components', 'Ductwork Components'),
    ('cooling_tower', 'Cooling Tower'),
    ('fire_suppression_system', 'Fire Suppression System'),
    ('gas_detection_system', 'Gas Detection System'),
    ('irrigation_system', 'Irrigation System'),
    ('exhaust_fan', 'Exhaust Fan'),
    ('vibration_isolator', 'Vibration Isolator'),
    ('filtration_system', 'Filtration System'),
    ('humidifier', 'Humidifier'),
    ('dehumidifier', 'Dehumidifier'),
    ('air_purifier', 'Air Purifier'),
    ('roof_top_unit', 'Rooftop Unit')
)
PLUMBING_EQUIPMENT_TYPES = (
    ('water_heater', 'Water Heater'),
    ('pump', 'Pump'),
    ('valve', 'Valve'),
    ('pipe_fittings', 'Pipe Fittings'),
    ('pressure_reducing_valve', 'Pressure Reducing Valve'),
    ('backflow_preventer', 'Backflow Preventer'),
    ('water_softener', 'Water Softener'),
    ('drainage_system', 'Drainage System'),
    ('faucet', 'Faucet'),
    ('toilet', 'Toilet'),
    ('irrigation_controller', 'Irrigation Controller'),
    ('sump_pump', 'Sump Pump'),
    ('greywater_system', 'Greywater System'),
    ('rainwater_harvesting_system', 'Rainwater Harvesting System'),
    ('sewage_pump', 'Sewage Pump'),
    ('water_recycling_system', 'Water Recycling System'),
    ('water_filtration', 'Water Filtration System'),
    ('sensor_faucet', 'Sensor Faucet'),
    ('emergency_shower', 'Emergency Shower'),
    ('eye_wash_station', 'Eye Wash Station')
)
MANUFACTURERS = (
    ('siemens', 'Siemens'),
    ('general_electric', 'General Electric'),
    ('honeywell', 'Honeywell'),
    ('trane', 'Trane'),
    ('carrier', 'Carrier'),
    ('bosch', 'Bosch'),
    ('abb', 'ABB'),
    ('schneider_electric', 'Schneider Electric'),
    ('mitsubishi_electric', 'Mitsubishi Electric'),
    ('johnson_controls', 'Johnson Controls'),
    ('daikin', 'Daikin'),
    ('emerson', 'Emerson'),
    ('hitachi', 'Hitachi'),
    ('toshiba', 'Toshiba'),
    ('rheem', 'Rheem'),
    ('kohler', 'Kohler'),
    ('moen', 'Moen'),
    ('delta', 'Delta'),
    ('grohe', 'Grohe'),
    ('american_standard', 'American Standard'),
    ('lennox', 'Lennox'),
    ('york', 'York'),
    ('goodman', 'Goodman'),
    ('lg', 'LG'),
    ('fujitsu', 'Fujitsu'),
    ('bryant', 'Bryant'),
    ('armstrong', 'Armstrong'),
    ('panasonic', 'Panasonic'),
    ('frigidaire', 'Frigidaire'),
    ('maytag', 'Maytag')
)


UNITS_OF_MEASURE = (
    ('kwh', 'Kilowatt hours'),
    ('kw', 'Kilowatts'),
    ('therms', 'Therms'),
    ('gallons', 'Gallons'),
    ('BTUH', 'British Thermal Units per hour'),
    ('sqft', 'Square Feet'),
    ('CO2e', 'Carbon Dioxide Equivalent'),
    ('lbs', 'Pounds'),
    ('kWh/sqft', 'Kilowatt hours per square foot'),
    ('kBTU/sqft', 'kilo British Thermal Units per square foot'),
    ('kWh/student', 'Kilowatt hours per student'),
    ('kBTU/student', 'kilo British Thermal Units per student'),
    ('$/sqft', 'Dollars per square foot'),
    ('$/student', 'Dollars per student'),
    ('lbs CO2e/sqft', 'Pounds of CO2e per square foot'),
    ('lbs CO2e/student', 'Pounds of CO2e per student'),
)
UNIT_CONVERSIONS = (
    ('lbs/metric_ton', 2204.62),
    ('BTU/kWh', 0.00029307),
    ('kBTU/kWh', 0.29307),
    ('kWh/kBTU', 3.412),
    ('kWh/MMBTU', 0.03412),
    ('kBTU/therm', 99.976),
    ('MMBTU/therm', 0.100),
    ('kWh/MWh', 0.001),
    ('CO2/CO2e', 1.0),
    ('CH4/CO2e', 25.0),
    ('CAMX(lbs CO2e/MWh)', 531.7),
    ('CAMX(lbs CO2e/kWh)', 0.532),
    ('CAMX GHG Factor, kg CO2e/kWh', 0.276),
    ('Methane(kBTU/lbs) NH4 natural gas', 23.81),
    ('Methane (lbs/kBTU) NH4 natural gas', 0.042),
)

MONTHS = (
    ('January', 'January'),
    ('February', 'February'),
    ('March', 'March'),
    ('April', 'April'),
    ('May', 'May'),
    ('June', 'June'),
    ('July', 'July'),
    ('August', 'August'),
    ('September', 'September'),
    ('October', 'October'),
    ('November', 'November'),
    ('December', 'December'),
)