# Generated by Django 5.0 on 2024-01-26 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('report', 'Report'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('letter', 'Letter'), ('manual', 'Manual'), ('policy_document', 'Policy Document'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet'), ('diagram', 'Diagram'), ('memo', 'Memo')], max_length=100)),
                ('document_format', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC/DOCX (Word Document)'), ('xls', 'XLS/XLSX (Excel Spreadsheet)'), ('ppt', 'PPT/PPTX (PowerPoint Presentation)'), ('txt', 'TXT (Text File)'), ('csv', 'CSV (Comma-Separated Values)'), ('jpeg', 'JPEG/JPG (Image File)'), ('png', 'PNG (Image File)'), ('gif', 'GIF (Image File)'), ('zip', 'ZIP (Compressed File)')], max_length=50)),
                ('document_description', models.TextField(max_length=250)),
                ('document_filepath', models.FileField(upload_to='documents/')),
                ('document_upload_date', models.DateTimeField(auto_now_add=True)),
                ('historical_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('historical_school', models.CharField(blank=True, max_length=100, null=True)),
                ('historical_equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('document_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.building')),
                ('document_equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.equipment')),
                ('document_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.school')),
            ],
        ),
    ]
