# Generated by Django 5.0 on 2024-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_description',
            field=models.TextField(default='document_description', max_length=250),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_filepath',
            field=models.FileField(default='document_path', upload_to='documents/'),
        ),
    ]
