# Generated by Django 5.0 on 2024-01-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_document_description_and_more'),
        ('school_management', '0008_building_building_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.building'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.equipment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_filepath',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
