# Generated by Django 5.0 on 2024-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_student_percent_low_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_student_percent_disenfrachised',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_student_population',
            field=models.IntegerField(default=0),
        ),
    ]
