# Generated by Django 5.0 on 2024-01-27 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_student_percent_low_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_geo_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_geo_long',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.CharField(default='building_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('classroom', 'Classroom Building'), ('laboratory', 'Laboratory'), ('library', 'Library'), ('restrooms', 'Restrooms'), ('cafeteria', 'Cafeteria'), ('gymnasium', 'Gymnasium'), ('auditorium', 'Auditorium'), ('administrative', 'Administrative'), ('maintenance', 'Maintenance'), ('storage', 'Storage'), ('parking', 'Parking'), ('sports', 'Sports'), ('playground', 'Playground'), ('outdoor', 'Outdoor'), ('other', 'Other'), ('arts', 'Arts'), ('music', 'Music'), ('theater', 'Theater'), ('workshop', 'Workshop'), ('kitchen', 'Kitchen'), ('health', 'Health'), ('counseling', 'Counseling'), ('security', 'Security'), ('energy_plant', 'Energy Plant'), ('commons', 'Student Commons/Common Area'), ('computer_lab', 'Computer Lab'), ('science_center', 'Science Center'), ('art_studio', 'Art Studio'), ('language_lab', 'Language Lab'), ('greenhouse', 'Greenhouse'), ('childcare', 'Childcare Center'), ('outdoor_classroom', 'Outdoor Classroom'), ('student_center', 'Student Center'), ('technology_hub', 'Technology Hub'), ('vocational_training', 'Vocational Training Center')], max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_student_percent_disenfrachised',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_student_population',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_uid', models.IntegerField(primary_key=True, serialize=False)),
                ('meter_utility_provider', models.CharField(choices=[('pg_e', 'PG&E')], max_length=100)),
                ('meter_utility_service_id', models.IntegerField()),
                ('meter_utility_billing_account', models.IntegerField()),
                ('meter_utility_service_address', models.CharField(max_length=100)),
                ('meter_utility_meter_number', models.IntegerField()),
                ('meter_utility_tariff_name', models.CharField(max_length=100)),
                ('meter_interval_start', models.DateTimeField()),
                ('meter_interval_end', models.DateTimeField()),
                ('meter_interval_kwh', models.FloatField(default=0.0)),
                ('meter_fwd_kwh', models.FloatField(default=0.0)),
                ('meter_net_kwh', models.FloatField(default=0.0)),
                ('meter_rev_kwh', models.FloatField(default=0.0)),
                ('meter_source', models.CharField(max_length=100)),
                ('meter_updated', models.DateTimeField()),
                ('meter_interval_timezone', models.CharField(choices=[('us_pacific', 'US/Pacific')], default='us_pacific', max_length=100)),
                ('meter_type', models.CharField(choices=[('gas', 'Gas'), ('electric', 'Electric'), ('water', 'Water'), ('steam', 'Steam'), ('chilled_water', 'Chilled Water'), ('hot_water', 'Hot Water'), ('fuel_oil', 'Fuel Oil'), ('other', 'Other')], default='meter_type', max_length=100)),
                ('meter_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.building', verbose_name='Associated Building')),
            ],
        ),
    ]
