# Generated by Django 5.0 on 2024-01-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_school_school_student_percent_low_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='meter_type',
        ),
    ]
