# Generated by Django 5.0 on 2024-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_remove_meter_meter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_photo',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_photo',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_geo_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_geo_long',
            field=models.FloatField(default=0.0),
        ),
    ]
