# Generated by Django 5.0 on 2024-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0004_remove_building_building_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_elec_kw_demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_gas_btuh_demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_generates_elec_kw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_location',
            field=models.CharField(default='equipment_location', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model',
            field=models.CharField(default='equipment_model', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_notes',
            field=models.TextField(blank=True, default='equipment_notes', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_serial_number',
            field=models.CharField(default='equipment_serial_number', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_storage_btu_kwh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_tag',
            field=models.CharField(default='equipment_tag', max_length=100),
        ),
    ]
