# Generated by Django 5.0 on 2024-01-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0006_alter_equipment_equipment_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_storage_btu_kwh',
            new_name='equipment_storage_kbtu',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_storage_kwh',
            field=models.IntegerField(default=0),
        ),
    ]
