# Generated by Django 5.0 on 2024-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0008_building_building_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='meter_fwd_kwh',
            new_name='meter_fwd_kwh_usage',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='meter_interval_kwh',
            new_name='meter_interval_kwh_usage',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='meter_net_kwh',
            new_name='meter_net_kwh_usage',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='meter_rev_kwh',
            new_name='meter_rev_kwh_usage',
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric'), ('water', 'Water'), ('steam', 'Steam'), ('chilled_water', 'Chilled Water'), ('hot_water', 'Hot Water'), ('fuel_oil', 'Fuel Oil'), ('other', 'Other')], default='meter_type', max_length=100),
        ),
    ]
