# Generated by Django 5.0 on 2024-02-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0009_rename_meter_fwd_kwh_meter_meter_fwd_kwh_usage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='meter_fwd_kwh',
            new_name='meter_fwd_kwh_usage',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='meter_interval_kwh',
            new_name='meter_interval_kwh_usage',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='meter_net_kwh',
            new_name='meter_net_kwh_usage',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='meter_rev_kwh',
            new_name='meter_rev_kwh_usage',
        ),
    ]
