# Generated by Django 5.0 on 2024-02-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0011_rename_school_student_percent_disenfrachised_school_school_student_percent_disadvantaged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_start_date', models.DateField()),
                ('bill_end_date', models.DateField()),
                ('bill_total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill_elec_consumption_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill_gas_consumption_mmbtu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill_water_consumption_gallons', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meter_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.meter')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
            ],
        ),
    ]
