# Generated by Django 5.0 on 2024-02-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0013_rename_bill_elec_consumption_kwh_utilitybill_elec_consumption_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='net_cost_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='net_elec_consumption_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='solar_energy_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='solar_generation_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='utility_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric')], default='electric', max_length=100),
        ),
    ]
