# Generated by Django 5.0 on 2024-02-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0014_performancemetrics_net_cost_dollars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitybill',
            name='bill_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='bill_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='meter_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='utility_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric')], max_length=100),
        ),
    ]
