# Generated by Django 5.0 on 2024-02-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0015_alter_utilitybill_bill_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='acount_number',
            field=models.IntegerField(default=0),
        ),
    ]
