# Generated by Django 5.0 on 2024-02-13 03:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_management', '0002_rename_district_bb_bottom_left_lat_schooldistrict_district_bb_northeast_lat_and_more'),
        ('school_management', '0016_utilitybill_acount_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='meter_uid',
            new_name='meter_id',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_fwd_kwh_usage',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_interval_end',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_interval_kwh_usage',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_interval_start',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_interval_timezone',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_net_kwh_usage',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_rev_kwh_usage',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_source',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_updated',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_utility_billing_account',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_utility_meter_number',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_utility_provider',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_utility_service_address',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_utility_service_id',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_utility_tariff_name',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='acount_number',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='elec_consumption_kwh',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='gas_consumption_therms',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='off_peak_demand_kwh',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='peak_demand_kwh',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='solar_generation_kwh',
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.school'),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='bill_statement_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='district_management.schooldistrict'),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='total_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.building'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric'), ('solar', 'Solar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='meter_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.meter'),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='utility_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric'), ('solar', 'Solar')], max_length=100),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elec_consumption_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gas_consumption_therms', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('peak_demand_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('off_peak_demand_kwh', models.IntegerField(default=0)),
                ('part_peak_demand_kwh', models.IntegerField(default=0)),
                ('demand_charge_kw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('solar_generation_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.meter')),
                ('utility_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.utilitybill')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('service_agreement_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('utility_type', models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric'), ('solar', 'Solar')], max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
            ],
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='service_agreement_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.serviceagreement'),
        ),
        migrations.CreateModel(
            name='UtilityProviderAccountNumber',
            fields=[
                ('account_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('utility_provider', models.CharField(choices=[('pg_e', 'Pacific Gas & Electric'), ('sce', 'Souther CA Edison')], max_length=100)),
                ('utility_type', models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric'), ('solar', 'Solar')], max_length=100)),
                ('account_district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='district_management.schooldistrict')),
            ],
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='utility_provider_account_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.utilityprovideraccountnumber', verbose_name='Associated Utility Provider Account Number'),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='account_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.utilityprovideraccountnumber'),
        ),
    ]
