# Generated by Django 5.0 on 2024-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0017_rename_meter_uid_meter_meter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitybill',
            name='meter_id',
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='total_demand_charge_kw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='total_solar_generation_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='total_usage_therms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
