# Generated by Django 5.0 on 2024-02-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0018_remove_utilitybill_meter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitybill',
            name='account_number',
        ),
    ]
