# Generated by Django 5.0 on 2024-02-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0019_remove_utilitybill_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='off_peak_demand_kwh',
            new_name='off_peak_consumption_kwh',
        ),
        migrations.RenameField(
            model_name='meterreading',
            old_name='part_peak_demand_kwh',
            new_name='part_peak_consumption_kwh',
        ),
        migrations.RenameField(
            model_name='meterreading',
            old_name='peak_demand_kwh',
            new_name='peak_consumption_kwh',
        ),
        migrations.RenameField(
            model_name='utilitybill',
            old_name='total_usage_kwh',
            new_name='total_electric_usage_kwh',
        ),
        migrations.RenameField(
            model_name='utilitybill',
            old_name='total_usage_therms',
            new_name='total_gas_usage_therms',
        ),
    ]
