# Generated by Django 5.0 on 2024-02-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0020_rename_off_peak_demand_kwh_meterreading_off_peak_consumption_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='meter_service_agreement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.serviceagreement'),
        ),
    ]
