# Generated by Django 5.0 on 2024-02-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0021_meter_meter_service_agreement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='total_off_peak_consumption_kwh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='total_part_peak_consumption_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='total_peak_consumption_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
