# Generated by Django 5.0 on 2024-02-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0022_utilitybill_total_off_peak_consumption_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='utility_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='utility_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilityprovideraccountnumber',
            name='utility_type',
            field=models.CharField(choices=[('natural_gas', 'Natural Gas'), ('electric', 'Electric')], max_length=100),
        ),
    ]
