# Generated by Django 5.0 on 2024-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0023_alter_meter_meter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityprovideraccountnumber',
            name='utility_provider',
            field=models.CharField(choices=[('pg_e', 'PGE'), ('sce', 'SCE'), ('socal_gas', 'SoCalG'), ('sdge', 'SDGE')], max_length=100),
        ),
    ]
