# Generated by Django 5.0 on 2024-02-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0024_alter_utilityprovideraccountnumber_utility_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_area_sqft',
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='utility_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='utility_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilityprovideraccountnumber',
            name='utility_provider',
            field=models.CharField(choices=[('PGE', 'PGE'), ('SCE', 'SCE'), ('SoCalG', 'SoCalG'), ('SDGE', 'SDGE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilityprovideraccountnumber',
            name='utility_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric')], max_length=100),
        ),
    ]
