# Generated by Django 5.0 on 2024-02-14 23:42

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import now

def default_current_datetime():
    """Returns the current datetime as an ISO formatted string."""
    return now().isoformat()

class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0025_remove_school_school_area_sqft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_geo_lat',
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_geo_long',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_geo_lat',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_geo_long',
        ),
        migrations.AddField(
            model_name='building',
            name='building_coordinates',
            field=models.JSONField(default=default_current_datetime),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_coordinates',
            field=models.JSONField(default=default_current_datetime),
            preserve_default=False,
        ),
    ]
