# Generated by Django 5.0 on 2024-02-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0026_remove_building_building_geo_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_coordinates',
            new_name='equipment_geo_coordinates',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_location',
        ),
    ]
