# Generated by Django 5.0 on 2024-02-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0027_rename_equipment_coordinates_equipment_equipment_geo_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_location',
            field=models.CharField(default='equipment_location', max_length=100),
        ),
    ]
