# Generated by Django 5.0 on 2024-02-15 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0028_equipment_equipment_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_geo_coordinates',
            new_name='equipment_coordinates',
        ),
    ]
