# Generated by Django 5.0 on 2024-02-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0029_rename_equipment_geo_coordinates_equipment_equipment_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric'), ('Solar', 'Solar')], max_length=100),
        ),
    ]
