# Generated by Django 5.0 on 2024-02-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0031_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='assigned_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=100),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='elec_bill_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elec_bill_id', to='school_management.utilitybill'),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='gas_bill_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_bill_id', to='school_management.utilitybill'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric'), ('net_energy', 'Net Energy Meter')], max_length=100),
        ),
    ]
