# Generated by Django 5.0 on 2024-02-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0032_performancemetrics_assigned_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric'), ('Electric-Net-Energy', 'Electric-Net-Energy'), ('net_energy', 'Net Energy Meter')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='utility_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric'), ('Electric-Net-Energy', 'Electric-Net-Energy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='utility_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric'), ('Electric-Net-Energy', 'Electric-Net-Energy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilityprovideraccountnumber',
            name='utility_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Electric', 'Electric'), ('Electric-Net-Energy', 'Electric-Net-Energy')], max_length=100),
        ),
    ]
