# Generated by Django 5.0 on 2024-02-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0035_remove_meter_meter_school_remove_meter_meter_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='scope1_co2e_gas_lbs',
            new_name='scope1_co2e_gas_lbs_ch4',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='scope2_co2e_elec_lbs',
            new_name='scope2_co2e_elec_lbs_camx',
        ),
    ]
