# Generated by Django 5.0 on 2024-02-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0036_rename_scope1_co2e_gas_lbs_performancemetrics_scope1_co2e_gas_lbs_ch4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_scope1_gas_lbs_co2e_sqft',
            new_name='cui_scope1_gas_lbs_co2e_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_scope1_gas_lbs_co2e_student',
            new_name='cui_scope1_gas_lbs_co2e_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_scope2_elec_lbs_co2e_sqft',
            new_name='cui_scope2_elec_lbs_co2e_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_scope2_elec_lbs_co2e_student',
            new_name='cui_scope2_elec_lbs_co2e_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_total_lbs_co2e_sqft',
            new_name='cui_total_lbs_co2e_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_total_lbs_co2e_student',
            new_name='cui_total_lbs_co2e_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='elec_energy_cost_index_dollar_sqft',
            new_name='elec_energy_cost_index_dollar_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='elec_energy_cost_index_dollar_student',
            new_name='elec_energy_cost_index_dollar_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='elec_energy_intensity_kwh_sqft',
            new_name='elec_energy_intensity_kwh_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='elec_energy_intensity_kwh_student',
            new_name='elec_energy_intensity_kwh_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='energy_cost_index_combined_dollar_student',
            new_name='energy_cost_index_combined_dollar_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='energy_cost_index_combined_dollar_sqft',
            new_name='energy_cost_index_combined_dollar_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='energy_use_intensity_combined_kbtu_sqft',
            new_name='energy_use_intensity_combined_kbtu_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='energy_use_intensity_combined_kbtu_student',
            new_name='energy_use_intensity_combined_kbtu_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='gas_energy_cost_index_dollar_sqft',
            new_name='gas_energy_cost_index_dollar_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='gas_energy_cost_index_dollar_student',
            new_name='gas_energy_cost_index_dollar_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='gas_energy_intensity_kbtu_sqft',
            new_name='gas_energy_intensity_kbtu_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='gas_energy_intensity_kbtu_student',
            new_name='gas_energy_intensity_kbtu_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='lbs_co2_per_lb_nh4',
            new_name='lbs_co2e_per_lb_natural_gas_ch4',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='lbs_natural_gas_nh4',
            new_name='lbs_natural_gas_ch4',
        ),
    ]
