# Generated by Django 5.0 on 2024-02-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0037_rename_cui_scope1_gas_lbs_co2e_sqft_performancemetrics_cui_scope1_gas_lbs_co2e_per_sqft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='energy_cost_index_combined_dollar_per_sqft',
            new_name='combined_energy_use_cost_index_dollar_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='energy_cost_index_combined_dollar_per_student',
            new_name='combined_energy_use_cost_index_dollar_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='energy_use_intensity_combined_kbtu_per_sqft',
            new_name='combined_energy_use_intensity_kbtu_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='energy_use_intensity_combined_kbtu_per_student',
            new_name='combined_energy_use_intensity_kbtu_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_scope1_gas_lbs_co2e_per_sqft',
            new_name='cui_scope1_lbs_co2e_per_sqft_from_natural_gas_use',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_scope1_gas_lbs_co2e_per_student',
            new_name='cui_scope1_lbs_co2e_per_student_from_natural_gas_use',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_scope2_elec_lbs_co2e_per_sqft',
            new_name='cui_scope2_lbs_co2e_per_sqft_from_elec_use',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='cui_scope2_elec_lbs_co2e_per_student',
            new_name='cui_scope2_lbs_co2e_per_student_from_elec_use',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='elec_energy_cost_index_dollar_per_sqft',
            new_name='elec_energy_use_cost_index_dollar_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='elec_energy_cost_index_dollar_per_student',
            new_name='elec_energy_use_cost_index_dollar_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='elec_energy_intensity_kwh_per_student',
            new_name='elec_energy_use_intensity_kwh_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='lbs_natural_gas_ch4',
            new_name='lbs_natural_gas_from_therms',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='gas_energy_cost_index_dollar_per_sqft',
            new_name='natural_gas_energy_use_cost_index_dollar_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='gas_energy_cost_index_dollar_per_student',
            new_name='natural_gas_energy_use_cost_index_dollar_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='gas_energy_intensity_kbtu_per_sqft',
            new_name='natural_gas_energy_use_intensity_kbtu_per_sqft',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='gas_energy_intensity_kbtu_per_student',
            new_name='natural_gas_energy_use_intensity_kbtu_per_student',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='lbs_co2e_per_lb_natural_gas_ch4',
            new_name='scope1_lbs_co2e_from_lbs_natural_gas',
        ),
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='scope2_co2e_elec_lbs_camx',
            new_name='scope2_lbs_co2e_from_kwh_elec_camx_grid',
        ),
        migrations.RemoveField(
            model_name='performancemetrics',
            name='elec_energy_intensity_kwh_per_sqft',
        ),
        migrations.RemoveField(
            model_name='performancemetrics',
            name='scope1_co2e_gas_lbs_ch4',
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='elec_energy_use_intensity_kbtu_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='elec_energy_use_intensity_kbtu_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
