# Generated by Django 5.0 on 2024-02-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0038_rename_energy_cost_index_combined_dollar_per_sqft_performancemetrics_combined_energy_use_cost_index_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilitybill',
            old_name='total_electric_charges',
            new_name='total_electric_charges_dollars',
        ),
        migrations.RenameField(
            model_name='utilitybill',
            old_name='total_gas_charges',
            new_name='total_gas_charges_dollars',
        ),
    ]
