# Generated by Django 5.0 on 2024-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0039_rename_total_electric_charges_utilitybill_total_electric_charges_dollars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilitybill',
            old_name='solar_energy_credits',
            new_name='electric_net_energy_meter_charges_dollars',
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='electric_net_off_peak_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='electric_net_part_peak_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='electric_net_peak_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='electric_net_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='estimated_total_net_energy_meter_charges_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='solar_energy_credits_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='solar_exports_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='solar_imports_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
