# Generated by Django 5.0 on 2024-02-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0040_rename_solar_energy_credits_utilitybill_electric_net_energy_meter_charges_dollars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('middle_school', 'Middle School'), ('high_school', 'High School'), ('elementary_school', 'Elementary School')], default='school-type', max_length=100),
            preserve_default=False,
        ),
    ]
