# Generated by Django 5.0 on 2024-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0041_school_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('adult_school', 'Adult School'), ('pre_school', 'Pre-School'), ('elementary_school', 'Elementary School'), ('middle_school', 'Middle School'), ('special_education_school', 'Special Education School'), ('high_school', 'High School'), ('miscellaneous', 'Miscellaneous')], max_length=100),
        ),
    ]
