# Generated by Django 5.0 on 2024-02-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0042_alter_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='assigned_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('elementary_school', 'Elementary School'), ('high_school', 'High School'), ('middle_school', 'Middle School'), ('adult_school', 'Adult School'), ('miscellaneous', 'Miscellaneous'), ('pre_school', 'Pre-School'), ('special_education_school', 'Special Education School')], max_length=100),
        ),
    ]
