# Generated by Django 5.0 on 2024-02-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0043_performancemetrics_assigned_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('miscellaneous', 'Miscellaneous'), ('special_education_school', 'Special Education School'), ('pre_school', 'Pre-School'), ('middle_school', 'Middle School'), ('adult_school', 'Adult School'), ('high_school', 'High School'), ('elementary_school', 'Elementary School')], max_length=100),
        ),
    ]
