# Generated by Django 5.0 on 2024-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0046_alter_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_has_solar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('middle_school', 'Middle School'), ('pre_school', 'Pre-School'), ('special_education_school', 'Special Education School'), ('high_school', 'High School'), ('elementary_school', 'Elementary School'), ('adult_school', 'Adult School'), ('miscellaneous', 'Miscellaneous')], max_length=100),
        ),
    ]
