# Generated by Django 5.0 on 2024-03-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0047_school_school_has_solar_alter_school_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='demand_charge_kw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='elec_consumption_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='gas_consumption_therms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='peak_consumption_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='solar_generation_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='combined_energy_use_cost_index_dollar_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='combined_energy_use_cost_index_dollar_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='combined_energy_use_intensity_kbtu_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='combined_energy_use_intensity_kbtu_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='cui_scope1_lbs_co2e_per_sqft_from_natural_gas_use',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='cui_scope1_lbs_co2e_per_student_from_natural_gas_use',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='cui_scope2_lbs_co2e_per_sqft_from_elec_use',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='cui_scope2_lbs_co2e_per_student_from_elec_use',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='cui_total_lbs_co2e_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='cui_total_lbs_co2e_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='elec_energy_use_cost_index_dollar_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='elec_energy_use_cost_index_dollar_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='elec_energy_use_intensity_kbtu_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='elec_energy_use_intensity_kbtu_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='elec_energy_use_intensity_kwh_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='elec_energy_use_intensity_kwh_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='lbs_natural_gas_from_therms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='natural_gas_energy_use_cost_index_dollar_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='natural_gas_energy_use_cost_index_dollar_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='natural_gas_energy_use_intensity_kbtu_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='natural_gas_energy_use_intensity_kbtu_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='net_cost_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='net_elec_consumption_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='scope1_lbs_co2e_from_lbs_natural_gas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='scope2_lbs_co2e_from_kwh_elec_camx_grid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('elementary_school', 'Elementary School'), ('adult_school', 'Adult School'), ('pre_school', 'Pre-School'), ('special_education_school', 'Special Education School'), ('high_school', 'High School'), ('middle_school', 'Middle School'), ('miscellaneous', 'Miscellaneous')], max_length=100),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='electric_net_energy_meter_charges_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='electric_net_off_peak_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='electric_net_part_peak_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='electric_net_peak_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='electric_net_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='estimated_total_net_energy_meter_charges_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='solar_energy_credits_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='solar_exports_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='solar_imports_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_demand_charge_kw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_electric_charges_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_electric_usage_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_gas_charges_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_gas_usage_therms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_peak_consumption_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_solar_generation_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
