# Generated by Django 5.0 on 2024-03-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0049_alter_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='total_scope1_and_2_lbs_co2e',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('high_school', 'High School'), ('miscellaneous', 'Miscellaneous'), ('adult_school', 'Adult School'), ('middle_school', 'Middle School'), ('elementary_school', 'Elementary School'), ('pre_school', 'Pre-School'), ('special_education_school', 'Special Education School')], max_length=100),
        ),
    ]
